### ISSUE TITLE
Ask for some details

### ISSUE THREAD

**Issue by keke-2000** [FanglinBao/HADAR#16] opened 2023-10-14 09:53 UTC
Hi, FanglinBao:
   Thank you very much to your lab for coming up with such groundbreaking results, which gave me some ideas that I can't wait to move forward with. After carefully reading your article, I currently have some questions and needs regarding the details in the supplementary material:

1. In section SIA of supplementary materials, the parameter table of the detector is shown. I want to know the dark noise term ξ and the σ term mentioned in it should include the influence of what factors, I think ξ should include the spontaneous radiation of the detector, the internal radiation of the camera box and the radiation of the filter wheel. And σ should include the electronic noise (Johnson-Nyquist noise, Flicker noise, etc.). Is it correct?
[1.png](https://postimg.cc/hzFKx0dq)
2. For the 0-49 channels of emiLib.mat and heatcube data used in the code, do they correspond to the range of wave number of 720-1250cm^-1 or the range of wavelength of 8-14μm? These two understandings are completely reversed.
3. In order to advance my idea, I really need the original data of optical diaphragm effect of the filter wheel mentioned in the supplementary material SIVB. I would be very appreciated if you could provide me with it.
[2.png](https://postimg.cc/v43zcPCc)

**Comment by FanglinBao** [comment] 2023-10-14 17:48
Hi Keke,
Very glad that you liked our work.
1. You are right. The dark noise term ξ includes contributions from the self-radiation of the system and the sensor. And σ accounts for the electronic noise.
2. All the data in the HADAR database is given in unit of wave number. (one exception is the test data in the TeX code package).
3. The optical diaphragm effect and corresponding data is only for HADAR prototype-1 experiments. It is irrelevant to HADAR prototype 2 or the synthetic data. If you are sure you still want that data (basically an image, calibrated for our setup), you can email me at: baof_at_purdue_dot_edu

**Comment by MeloHX** [comment] 2023-10-20 09:39
Hi,Fanglin Bao:
Congratulations to your lab for doing so well in this area. I read your article and code carefully, which gave me a lot of inspiration for my project "Texture enhancement of thermal infrared images". However, since there are not many public data sets in the scenario that my research is adapted to, I have been thinking about using blender to make synthetic data. Coincidentally, I found that your experimental data also has synthetic data based on blender. Although you gave a lot of details about the data, unfortunately, it seems that you did not give how to simulate with blender. I am really eager to know your method, I wonder if it is convenient for you to let me know?The details I want to know are: 
   1.blender involves attaching materials to objects, for example if I want to attach the material properties of aluminum to a block, then when I attach the material properties of the block, I need to attach the emissivity of aluminum to the self-emission properties of the block (so far this is how I think of it).But is his RGB attribute still needed? (including his RGB color, aluminum appearance, roughness, surface reflection value, etc.).
  2.Then,how to obtain the gt of the image I obtained, such as vmap,emap,xmap, etc., used in Tex-Net.
If you are willing to provide me with additional information, I would appreciate it very much and look forward to your reply

**Comment by FanglinBao** [comment] 2023-10-20 16:06
> Hi,Fanglin Bao: Congratulations to your lab for doing so well in this area. I read your article and code carefully, which gave me a lot of inspiration for my project "Texture enhancement of thermal infrared images". However, since there are not many public data sets in the scenario that my research is adapted to, I have been thinking about using blender to make synthetic data. Coincidentally, I found that your experimental data also has synthetic data based on blender. Although you gave a lot of details about the data, unfortunately, it seems that you did not give how to simulate with blender. I am really eager to know your method, I wonder if it is convenient for you to let me know?The details I want to know are: 1.blender involves attaching materials to objects, for example if I want to attach the material properties of aluminum to a block, then when I attach the material properties of the block, I need to attach the emissivity of aluminum to the self-emission properties of the block (so far this is how I think of it).But is his RGB attribute still needed? (including his RGB color, aluminum appearance, roughness, surface reflection value, etc.). 2.Then,how to obtain the gt of the image I obtained, such as vmap,emap,xmap, etc., used in Tex-Net. If you are willing to provide me with additional information, I would appreciate it very much and look forward to your reply

Hi MeloHX,
1, you'll need to match Blender parameters to the physics properties. For example, RGB gives you 3 channels to render your interested data in your wavelength. RGB color and reflection are where you assign the self emission and reflectance values according to your physics model. You'll need to tune the surface roughness as you want, etc.
2, For ground truth eMap & tMap, you can assign a uniform color to the same material and render it. You'll need to post-process to map the color to your material index... We used the ground truth eMap and tMap to solve vMap.

**Comment by MeloHX** [comment] 2023-10-26 07:30
Thank you for answering my question, I still have some confusion:
1. you mentioned "RGB color and reflection are where you assign the self emission and reflectance values", but what I understand is that thermal radiation is the ability of an object to emit energy, so it's not a visible light attribute, maybe I should assign "self-emission" to the emission color of a blender object instead of the RGB color attribute.
2. Can the data collected be less than 54 channels? What determines the channel number?
![base color](https://github.com/FanglinBao/HADAR/assets/114329754/62cc205f-7e5a-4cfe-ab08-c1d44621e9f1)

![base color](https://github.com/FanglinBao/HADAR/assets/114329754/46f2f179-1a06-410f-aee0-6132ba03576f)

**Comment by MeloHX** [comment] 2023-10-26 07:45
Thank you for answering my question, I still have some confusion:
1.you mentioned "RGB color and reflection are where you assign the self emission and reflectance values", but what I understand is that thermal radiation is the ability of an object to emit energy, so it's not a visible light attribute, maybe I should assign "self-emission" to the emission color of a blender object instead of the RGB color attribute.(as shown in the picture).Which is right?
2.If it is true to assign "self emission" to RGB color channels, the process would be as follows:
(1)_. Assign the same color to the same material to get eMap,tMap.(And the how to get vMap?)
(2). Calculate the self-emission of each material  and then re-assigned to the RGB color of the material.
(3). Render to get hyperspectral data.
3.Can the data collected be less than 54 channels? What determines the number of channel?
I am sorry that my questions are too trivial, and thank you for your patient response!
![base color](https://github.com/FanglinBao/HADAR/assets/114329754/dc6d2153-9f97-48a1-90e3-ab8e9b6b6198)

![emission](https://github.com/FanglinBao/HADAR/assets/114329754/dfd30347-fb38-4f1c-bfcb-706cb95b4050)

**Comment by MeloHX** [comment] 2023-10-26 10:27
Another problem is that after I attach a unique color to each material, the color on the object will change after rendering, and the same material will have different colors due to reflection and diffusion. In this case, how can I obtain the material index by reversely checking the color?

**Comment by FanglinBao** [comment] 2023-10-28 01:33
> Another problem is that after I attach a unique color to each material, the color on the object will change after rendering, and the same material will have different colors due to reflection and diffusion. In this case, how can I obtain the material index by reversely checking the color?

Please set the ray depth = 0 to disable scattering. You can check the README file in this database for more details.

**Comment by SnowLiu530** [comment] 2023-10-31 07:06
Hi Fanglin Bao:
I would like to express my heartfelt congratulations and admiration for your outstanding work on research. I have been closely following your progress, and I must say it is truly impressive.
I am writing to seek some assistance with a problem I encountered during the visualization process. Specifically, I have noticed that most of the TeX-GT images in my visualization are empty, appearing as completely black. Moreover, I have also observed the same phenomenon of empty TeX-GT images in the visualization results of the provided pre-trained models, particularly in the data located under the "supervised_synexp_r50_fold0_new_eval_visualized" . I am very curious to understand the underlying cause of this issue.
I would be immensely grateful if you could provide some insights and explanations regarding this matter.

**Comment by FanglinBao** [comment] 2023-11-01 15:09
> Hi Fanglin Bao: I would like to express my heartfelt congratulations and admiration for your outstanding work on research. I have been closely following your progress, and I must say it is truly impressive. I am writing to seek some assistance with a problem I encountered during the visualization process. Specifically, I have noticed that most of the TeX-GT images in my visualization are empty, appearing as completely black. Moreover, I have also observed the same phenomenon of empty TeX-GT images in the visualization results of the provided pre-trained models, particularly in the data located under the "supervised_synexp_r50_fold0_new_eval_visualized" . I am very curious to understand the underlying cause of this issue. I would be immensely grateful if you could provide some insights and explanations regarding this matter.

Thanks!
Can you load the 'empty' images and check the exact data value? We mainly work with the data values in the image files. I believe it is caused by the image format. Sometimes when you output values like 0.1 to a PNG image which only takes 0~255 integers, it will become black.

**Closed as completed** 2023-11-06 21:23 UTC

**Comment by czw1910** [comment] 2024-10-31 12:30
> Another problem is that after I attach a unique color to each material, the color on the object will change after rendering, and the same material will have different colors due to reflection and diffusion. In this case, how can I obtain the material index by reversely checking the color?
和咯哦

**Comment by czw1910** [comment] 2024-10-31 12:41
> Hi,Fanglin Bao: Congratulations to your lab for doing so well in this area. I read your article and code carefully, which gave me a lot of inspiration for my project "Texture enhancement of thermal infrared images". However, since there are not many public data sets in the scenario that my research is adapted to, I have been thinking about using blender to make synthetic data. Coincidentally, I found that your experimental data also has synthetic data based on blender. Although you gave a lot of details about the data, unfortunately, it seems that you did not give how to simulate with blender. I am really eager to know your method, I wonder if it is convenient for you to let me know?The details I want to know are: 1.blender involves attaching materials to objects, for example if I want to attach the material properties of aluminum to a block, then when I attach the material properties of the block, I need to attach the emissivity of aluminum to the self-emission properties of the block (so far this is how I think of it).But is his RGB attribute still needed? (including his RGB color, aluminum appearance, roughness, surface reflection value, etc.). 2.Then,how to obtain the gt of the image I obtained, such as vmap,emap,xmap, etc., used in Tex-Net. If you are willing to provide me with additional information, I would appreciate it very much and look forward to your reply

@MeloHX Hello, I have been trying to simulate infrared scenes on Blender recently. I encountered some difficulties in setting the material reflectivity. I was wondering if I could communicate with you. My email is 123104222727@njust.edu.cn Thank you.
